version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: chat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: chat
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://your_db_user:your_db_password@db:5432/chat
    ports:
      - "3000:3000"
    command: ["yarn", "start"]

volumes:
  db_data:
