CREATE TABLE Messages (
  id SERIAL PRIMARY KEY,
  senderId INTEGER,
  receiverId INTEGER,
  groupId INTEGER,
  content TEXT,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
