CREATE TABLE Groups (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255),
  creatorId INTEGER,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
